######################################################################
# Automatically generated by qmake (3.0) Sat Jan 21 21:56:39 2017
######################################################################

TEMPLATE = app
TARGET = graphic
INCLUDEPATH += .
QT += gui core widgets

# Input
HEADERS += include/GModule.hpp \
           include/GModuleDate.hpp \
           include/GModuleHostname.hpp \
           include/MainWindow.hpp
SOURCES += include/GModule.moc.cpp \
           include/GModuleDate.moc.cpp \
           include/GModuleHostname.moc.cpp \
           include/MainWindow.moc.cpp \
           source/GModule.cpp \
           source/GModuleDate.cpp \
           source/GModuleHostname.cpp \
           source/main.cpp \
           source/MainWindow.cpp
